### ISSUE TITLE
Use qhull for intersecting near-optimal spaces

### ISSUE THREAD

**Issue by aleks-g** [aleks-g/intersecting-near-opt-spaces#2]
Instead of probing directions, we could use qhull to compute intersections of near-optimal spaces:
http://www.qhull.org/html/qhalf.htm

The different halfspaces are defined by the equations given through the different polytopes, so it should be possible to just use all of these as input information for qhull. I think I remember that this was our initial approach, but the implementation suffered from performance issues. Maybe that won't happen with qhull?

**Comment by koen-vg** [comment]
Fixed in c9a7c034e4506e8143611ed6c1094e9d5a059a63
